spring:
  main:
    banner-mode: off
  flyway:
    table: schema_version
  datasource:
    url: jdbc:postgresql://${PAWVEILARBREGISTRERING_HOSTNAME}:${PAWVEILARBREGISTRERING_PORT}/veilarbregistrering
    username: ${PAWVEILARBREGISTRERING_USERNAME}
    password:  ${PAWVEILARBREGISTRERING_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /internal
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
